name: Build OQB-updater

on: 
  push:
  workflow_dispatch:

jobs:
  OQB-updater:
    runs-on: ubuntu-latest
    #container: hamletdufromage/devkita64_devkitarm
    container: devkitpro/devkita64
    steps:
    - uses: actions/checkout@v1

    - name: update repo
      run: |
        git config --global --add safe.directory /__w/OQB-updater/OQB-updater/lib/borealis
        git config --global --add safe.directory /__w/OQB-updater/OQB-updater
        git config --global --add safe.directory /__w/OQB-updater/OQB-updater/TegraExplorer
        git submodule update --init --recursive

    - name: install dependencies
      run: |
        dkp-pacman -S --needed --noconfirm switch-curl switch-zlib switch-mbedtls

    - name: Building OQB-updater
      run: |
        make -C aiosu-forwarder -f Makefile
        make -j$(nproc)
        
    - uses: actions/upload-artifact@master
      with:
        name: OQB-updater
        path: OQB-updater.nro

    - name: Crear zip para release
      run: zip OQB-updater.zip OQB-updater.nro

    - name: Publicar Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        name: Latest Build
        files: OQB-updater.zip
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
